export  const customerRows = [
    { 
        id:1,
        USERNAME:"danbra13",
        FullName:'Solomon Miles',
        AVATER:"http://thedreamwithinpictures.com/wp-content/uploads/2015/09/d3b95__IMG_3255.jpg",
        EMAIL:"nick@gmail.com",
        Phone_No:"134334433",
        STATUS:"Online",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"400",
     },
     { 
        id:2,
        USERNAME:"danbra14",
        FullName:'Dallas Fisher',
        AVATER:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmFuZG9tJTIwcGVvcGxlfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80",
        EMAIL:"seggzboykingman@gmail.com",
        Phone_No:"134334433",
        STATUS:"Offline",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"1200",
     },
     { 
        id:3,
        USERNAME:"danbra15",
        FullName:'Evan Hall',
        AVATER:"https://www.newsshare.in/wp-content/uploads/2/Anime-WhatsApp-DP-for-Girls-16.jpg",
        EMAIL:"swift@gmail.com",
        Phone_No:"134334433",
        STATUS:"Online",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"30",
     },
     { 
        id:4,
        USERNAME:"danbra16",
        FullName:'Solomon Miles',
        AVATER:"http://thedreamwithinpictures.com/wp-content/uploads/2015/09/d3b95__IMG_3255.jpg",
        EMAIL:"jon@gmail.com",
        Phone_No:"134334433",
        STATUS:"Online",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"5001",
     },
     { 
        id:5,
        USERNAME:"danbra17",
        FullName:'Connor Lawrence',
        AVATER:"http://thedreamwithinpictures.com/wp-content/uploads/2015/09/d3b95__IMG_3255.jpg",
        EMAIL:"sam@gmail.com",
        Phone_No:"134334433",
        STATUS:"Online",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"150",
     },
     { 
        id:6,
        USERNAME:"danbra18",
        FullName:'Solomon Miles',
        AVATER:"https://www.newsshare.in/wp-content/uploads/2/Anime-WhatsApp-DP-for-Girls-16.jpg",
        EMAIL:"swift@gmail.com",
        Phone_No:"134334433",
        STATUS:"Online",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"30",
     },
     { 
        id:7,
        USERNAME:"danbra19",
        FullName:'Khalil Green',
        AVATER:"http://thedreamwithinpictures.com/wp-content/uploads/2015/09/d3b95__IMG_3255.jpg",
        EMAIL:"jon@gmail.com",
        Phone_No:"134334433",
        STATUS:"Online",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"5001",
     },
     { 
        id:8,
        USERNAME:"danbra20",
        FullName:'Solomon Miles',
        AVATER:"https://www.newsshare.in/wp-content/uploads/2/Anime-WhatsApp-DP-for-Girls-16.jpg",
        EMAIL:"sam@gmail.com",
        Phone_No:"134334433",
        STATUS:"Online",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"150",
     },
     { 
        id:9,
        USERNAME:"danbra21",
        FullName:'Gale Lawson',
        AVATER:"http://thedreamwithinpictures.com/wp-content/uploads/2015/09/d3b95__IMG_3255.jpg",
        EMAIL:"jon@gmail.com",
        Phone_No:"134334433",
        STATUS:"Online",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"5001",
     },
     { 
        id:10,
        USERNAME:"danbra22",
        FullName:'Ash Jordan',
        AVATER:"http://thedreamwithinpictures.com/wp-content/uploads/2015/09/d3b95__IMG_3255.jpg",
        EMAIL:"sam@gmail.com",
        Phone_No:"134334433",
        STATUS:"Offline",
        DOB:"2021-12-08",
        Address:"Famagusa | TRNC",
        Company:"Stark Inc.",
        Position:"Jr. Dev",
        TRANSACTIONS:"1",
     },
  ];