export const CUSTOMER_ACTIVITY_DATA_REQUEST='CUSTOMER_ACTIVITY_DATA_REQUEST';
export const CUSTOMER_ACTIVITY_DATA_SUCCESS='CUSTOMER_ACTIVITY_DATA_SUCCESS';
export const CUSTOMER_ACTIVITY_DATA_FAIL='CUSTOMER_ACTIVITY_DATA_FAIL';

    