export const RETURN_LIST_REQUEST='RETURN_LIST_REQUEST';
export const RETURN_LIST_SUCCESS='RETURN_LIST_SUCCESS';
export const RETURN_LIST_FAIL='RETURN_LIST_FAIL';


export const RETURN_DETAILS_REQUEST='RETURN_DETAILS_REQUEST';
export const RETURN_DETAILS_SUCCESS='RETURN_DETAILS_SUCCESS';
export const RETURN_DETAILS_FAIL='RETURN_DETAILS_FAIL';